// <copyright file="frmMain.cs" company="None">
//    <para>
//    This work is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published
//    by the Free Software Foundation; either version 2 of the License,
//    or (at your option) any later version.</para>
//    <para>
//    This work is distributed in the hope that it will be useful, but
//    WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//    General Public License for more details.</para>
//    <para>
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
//    USA</para>
//    Based on code auto-generated by VS 2015.
//    Copyright (c) 2016 Jeremy Gibbons. All rights reserved
// </copyright>

namespace MibbleBrowser
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Windows.Forms;

    /// <summary>
    /// Partial class representing the main form of the <c>MibBrowser</c> application.
    /// </summary>
    public partial class FrmMain : Form
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FrmMain"/> class.
        /// </summary>
        public FrmMain()
        {
            this.InitializeComponent();
            this.mibTreeBuilder = new MibTreeBuilder(this.treeMibs);
            this.mibTreeBuilder.LoadMibFile("RFC1213-MIB");
            this.mibTreeBuilder.LoadMibFile("HOST-RESOURCES-MIB");
        }

        /// <summary>
        /// Event handler for MIB ToolStrip Menu Item
        /// </summary>
        /// <param name="sender">The sender</param>
        /// <param name="e">The event arguments</param>
        private void LoadMIBToolStripMenuItem_Click(object sender, EventArgs e)
        {
            DialogResult result = this.openFileDialogMain.ShowDialog();
            if (result == DialogResult.OK)
            {
                string file = openFileDialogMain.FileName;
                mibTreeBuilder.LoadMibFile(file);
            }
        }

        /// <summary>
        /// Event handler for NodeMouseClick event on MIB tree.
        /// </summary>
        /// <param name="sender">The event sender</param>
        /// <param name="e">The event arguments</param>
        private void TreeMibs_NodeMouseClick(object sender, TreeNodeMouseClickEventArgs e)
        {
            MibNode n = e.Node as MibNode;
            if (n == null)
            {
                return;
            }

            string t = string.Join(
                "\r\n", 
                n.Description
                .Split(new char[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(s => s.Trim()));

            txtNodeInfo.Text = t;
        }
    }
}
